apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::378582414855:role/Iteratec-Test-MK
      username: build
#      username: system:node:{{EC2PrivateDNSName}}
#      username: testuser
      groups:
        - system:masters
        - system:bootstrappers
        - system:nodes
