---
version: 0.2
phases:
  install:
    commands:
      - aws sts get-caller-identity
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS  --password-stdin 378582414855.dkr.ecr.eu-central-1.amazonaws.com
      - aws eks update-kubeconfig --name adyszy-eks-cluster --region eu-central-1 --role-arn arn:aws:iam::378582414855:role/ADyszyEksCodeBuildKubectlRole
      - kubectl get nodes

  pre_build:
    commands:
  build:
    commands:
  post_build:
    commands:
artifacts:
  files: build.json
