---
version: 0.2
phases:
  install:
    commands:
      - aws sts get-caller-identity
      - kubectl aws-auth-cm.yaml
      - kubectl get nodes

  pre_build:
    commands:
  build:
    commands:
  post_build:
    commands:
artifacts:
  files: build.json
