---
version: 0.2
phases:
  install:
    commands:
      - aws sts get-caller-identity
      - kubectl help
  pre_build:
    commands:
  build:
    commands:
  post_build:
    commands:
artifacts:
  files: build.json
